# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomerCrud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CustomerCrud.proto',
  package='com.rvbb.b2b.grpc.service',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x43ustomerCrud.proto\x12\x19\x63om.rvbb.b2b.grpc.service\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x0f\x43ustomerRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"k\n\x0c\x43ustomerData\x12\x14\n\x0c\x63ustomerName\x18\x01 \x01(\t\x12\x13\n\x0bmobilePhone\x18\x02 \x01(\t\x12\x0f\n\x07yearOld\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x03\x12\x13\n\x0b\x63reatedDate\x18\x05 \x01(\t\"y\n\x10\x43ustomerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x35\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\'.com.rvbb.b2b.grpc.service.CustomerData\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xd5\x03\n\x13\x43ustomerCrudService\x12\x61\n\x06\x63reate\x12*.com.rvbb.b2b.grpc.service.CustomerRequest\x1a+.com.rvbb.b2b.grpc.service.CustomerResponse\x12\x61\n\x06update\x12*.com.rvbb.b2b.grpc.service.CustomerRequest\x1a+.com.rvbb.b2b.grpc.service.CustomerResponse\x12T\n\x06\x64\x65lete\x12\x1d.com.rvbb.b2b.grpc.service.ID\x1a+.com.rvbb.b2b.grpc.service.CustomerResponse\x12R\n\x04read\x12\x1d.com.rvbb.b2b.grpc.service.ID\x1a+.com.rvbb.b2b.grpc.service.CustomerResponse\x12N\n\x07listAll\x12\x16.google.protobuf.Empty\x1a+.com.rvbb.b2b.grpc.service.CustomerResponseB\x02P\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CUSTOMERREQUEST = _descriptor.Descriptor(
  name='CustomerRequest',
  full_name='com.rvbb.b2b.grpc.service.CustomerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.rvbb.b2b.grpc.service.CustomerRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.rvbb.b2b.grpc.service.CustomerRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone', full_name='com.rvbb.b2b.grpc.service.CustomerRequest.phone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.rvbb.b2b.grpc.service.CustomerRequest.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=149,
)


_CUSTOMERDATA = _descriptor.Descriptor(
  name='CustomerData',
  full_name='com.rvbb.b2b.grpc.service.CustomerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerName', full_name='com.rvbb.b2b.grpc.service.CustomerData.customerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mobilePhone', full_name='com.rvbb.b2b.grpc.service.CustomerData.mobilePhone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yearOld', full_name='com.rvbb.b2b.grpc.service.CustomerData.yearOld', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='com.rvbb.b2b.grpc.service.CustomerData.id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createdDate', full_name='com.rvbb.b2b.grpc.service.CustomerData.createdDate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=258,
)


_CUSTOMERRESPONSE = _descriptor.Descriptor(
  name='CustomerResponse',
  full_name='com.rvbb.b2b.grpc.service.CustomerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='com.rvbb.b2b.grpc.service.CustomerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='com.rvbb.b2b.grpc.service.CustomerResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.rvbb.b2b.grpc.service.CustomerResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.rvbb.b2b.grpc.service.CustomerResponse.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=381,
)


_ID = _descriptor.Descriptor(
  name='ID',
  full_name='com.rvbb.b2b.grpc.service.ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.rvbb.b2b.grpc.service.ID.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=399,
)

_CUSTOMERRESPONSE.fields_by_name['data'].message_type = _CUSTOMERDATA
DESCRIPTOR.message_types_by_name['CustomerRequest'] = _CUSTOMERREQUEST
DESCRIPTOR.message_types_by_name['CustomerData'] = _CUSTOMERDATA
DESCRIPTOR.message_types_by_name['CustomerResponse'] = _CUSTOMERRESPONSE
DESCRIPTOR.message_types_by_name['ID'] = _ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerRequest = _reflection.GeneratedProtocolMessageType('CustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERREQUEST,
  '__module__' : 'CustomerCrud_pb2'
  # @@protoc_insertion_point(class_scope:com.rvbb.b2b.grpc.service.CustomerRequest)
  })
_sym_db.RegisterMessage(CustomerRequest)

CustomerData = _reflection.GeneratedProtocolMessageType('CustomerData', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERDATA,
  '__module__' : 'CustomerCrud_pb2'
  # @@protoc_insertion_point(class_scope:com.rvbb.b2b.grpc.service.CustomerData)
  })
_sym_db.RegisterMessage(CustomerData)

CustomerResponse = _reflection.GeneratedProtocolMessageType('CustomerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERRESPONSE,
  '__module__' : 'CustomerCrud_pb2'
  # @@protoc_insertion_point(class_scope:com.rvbb.b2b.grpc.service.CustomerResponse)
  })
_sym_db.RegisterMessage(CustomerResponse)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'CustomerCrud_pb2'
  # @@protoc_insertion_point(class_scope:com.rvbb.b2b.grpc.service.ID)
  })
_sym_db.RegisterMessage(ID)


DESCRIPTOR._options = None

_CUSTOMERCRUDSERVICE = _descriptor.ServiceDescriptor(
  name='CustomerCrudService',
  full_name='com.rvbb.b2b.grpc.service.CustomerCrudService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=402,
  serialized_end=871,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='com.rvbb.b2b.grpc.service.CustomerCrudService.create',
    index=0,
    containing_service=None,
    input_type=_CUSTOMERREQUEST,
    output_type=_CUSTOMERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='com.rvbb.b2b.grpc.service.CustomerCrudService.update',
    index=1,
    containing_service=None,
    input_type=_CUSTOMERREQUEST,
    output_type=_CUSTOMERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='com.rvbb.b2b.grpc.service.CustomerCrudService.delete',
    index=2,
    containing_service=None,
    input_type=_ID,
    output_type=_CUSTOMERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='com.rvbb.b2b.grpc.service.CustomerCrudService.read',
    index=3,
    containing_service=None,
    input_type=_ID,
    output_type=_CUSTOMERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listAll',
    full_name='com.rvbb.b2b.grpc.service.CustomerCrudService.listAll',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CUSTOMERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERCRUDSERVICE)

DESCRIPTOR.services_by_name['CustomerCrudService'] = _CUSTOMERCRUDSERVICE

# @@protoc_insertion_point(module_scope)
